name = "subscribetracker"
compatibility_date = "2024-01-01"

[assets]
directory = "./frontend/dist"

[build]
command = "npm run build:frontend"
publish = "frontend/dist"

[build.environment_variables]
NODE_VERSION = "18"
NPM_VERSION = "8"