name = "subscribetracker"
compatibility_date = "2024-01-01"

[build]
command = "cd frontend && npm install && npm run build"
publish = "frontend/dist"

[assets]
directory = "./frontend/dist"

[env.production]
JWT_SECRET = "your-jwt-secret"
DATABASE_URL = "your-database-url"
GEMINI_API_KEY = "your-gemini-api-key"
WECHAT_WEBHOOK_URL = "your-wechat-webhook-url"
DINGTALK_WEBHOOK_URL = "your-dingtalk-webhook-url"
TELEGRAM_BOT_TOKEN = "your-telegram-bot-token"
WXPUSHER_APP_TOKEN = "your-wxpusher-app-token"

[[kv_namespaces]]
binding = "SUBSCRIPTIONS_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[build.environment_variables]
NODE_VERSION = "18"